version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package.json and pnpm-lock.yaml
    schedule:
      interval: "weekly" # Can be "daily", "weekly", or "monthly"
    labels:
      - "dependencies"
    reviewers:
      - "cristianizzo"
      - "harryburger"
    assignees:
      - "cristianizzo"
      - "harryburger"
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto" # Auto-rebase when conflicts
    versioning-strategy: "increase"
    groups:
      minor-and-patch:
        update-types:
          - "patch"
          - "minor"

  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    reviewers:
      - "cristianizzo"
      - "harryburger"
    groups:
      minor-and-patch:
        update-types:
          - "patch"
          - "minor"
