version: '3.7'

services:
  ### Services

  service-api:
    build:
      context: ./
    ports:
      - ${SERVICE_API_PORT:-3000}:${SERVICE_API_PORT:-3000}
    environment:
      PORT: ${SERVICE_API_PORT:-3000}
    depends_on:
      - db
    env_file:
      - ./docker.env
    command: bash -c 'yarn wait:db & wait && yarn service:api'

  service-data-sync:
    build:
      context: ./
    depends_on:
      - db
    env_file:
      - ./docker.env
    command: bash -c 'yarn wait:db & wait && yarn service:data-sync'

  ### Dependencies

  db:
    image: mongo:7.0.0
    ports:
      - "27017:27017"
