version: '3.7'

services:
  ### Services

  service-aragon-api:
    build:
      context: ./
    ports:
      - ${SERVICE_API_PORT:-3000}:${SERVICE_API_PORT:-3000}
    environment:
      PORT: ${SERVICE_API_PORT:-3000}
    env_file:
      - ./.env
    command: bash -c 'yarn service:aragon-api'

  service-aragon-indexer:
    build:
      context: ./
    env_file:
      - ./.env
    command: bash -c 'yarn service:aragon-indexer'

  service-aragon-dao:
    build:
      context: ./
    env_file:
      - ./.env
    command: bash -c 'yarn service:aragon-dao'

  service-aragon-rates:
    build:
      context: ./
    env_file:
      - ./.env
    command: bash -c 'yarn service:aragon-rates'

  service-aragon-sync:
    build:
      context: ./
    env_file:
      - ./.env
    command: bash -c 'yarn service:aragon-sync'

  service-aragon-transactions:
    build:
      context: ./
    env_file:
      - ./.env
    command: bash -c 'yarn service:aragon-transactions'

  service-aragon-plugins:
    build:
      context: ./
    env_file:
      - ./.env
    command: bash -c 'yarn service:aragon-plugins'
