services:
  # --------------------------------------------------
  # RabbitMQ
  # --------------------------------------------------
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    container_name: rabbitmq-${ENV_SUFFIX}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}
    ports:
      - '${RABBITMQ_AMQP_PORT}:${RABBITMQ_AMQP_PORT}'               # AMQP port
      - '${RABBITMQ_MANAGEMENT_PORT}:${RABBITMQ_MANAGEMENT_PORT}'    # HTTP management UI
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmqctl status" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal-net

  # --------------------------------------------------
  # Migration Service (runs once and exits)
  # --------------------------------------------------
  migration:
    image: service-migration-${ENV_SUFFIX}
    container_name: service-migration-${ENV_SUFFIX}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.aragon-indexer-${ENV_SUFFIX} # Use the same env file as the indexer
    depends_on:
      rabbitmq:
        condition: service_healthy
    command: bash -c "yarn wait:rabbitmq && yarn mig:run && echo 'Migration Service completed'"
    restart: "no"  # Don't restart after completion
    networks:
      - internal-net

  # --------------------------------------------------
  # Microservices
  # --------------------------------------------------
  service-aragon-api:
    image: service-aragon-api-${ENV_SUFFIX}
    container_name: service-aragon-api-${ENV_SUFFIX}
    build:
      context: .
    ports:
      - '${SERVICES_API_PORT}:${SERVICES_API_PORT}'
    env_file:
      - .env.aragon-api-${ENV_SUFFIX}
    depends_on:
      - rabbitmq
    command: bash -c "yarn wait:rabbitmq && yarn service:aragon-api"
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:${SERVICES_API_PORT}/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal-net
      - public-net

  service-aragon-admin-api:
    image: service-aragon-admin-api-${ENV_SUFFIX}
    container_name: service-aragon-admin-api-${ENV_SUFFIX}
    build:
      context: .
    ports:
      - '${SERVICES_ADMIN_API_PORT}:${SERVICES_ADMIN_API_PORT}'
    env_file:
      - .env.aragon-admin-api-${ENV_SUFFIX}
    depends_on:
      - rabbitmq
    command: bash -c "yarn wait:rabbitmq && yarn service:aragon-admin-api"
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:${SERVICES_ADMIN_API_PORT}/health || exit 1']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal-net
      - public-net

  service-aragon-indexer:
    image: service-aragon-indexer-${ENV_SUFFIX}
    container_name: service-aragon-indexer-${ENV_SUFFIX}
    build:
      context: .
    env_file:
      - .env.aragon-indexer-${ENV_SUFFIX}
    depends_on:
      - rabbitmq
    command: bash -c "yarn wait:rabbitmq && yarn service:aragon-indexer"
    healthcheck:
      test: ['CMD-SHELL', "pgrep -f 'service:aragon-indexer' > /dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal-net
      - public-net

  service-aragon-dao:
    image: service-aragon-dao-${ENV_SUFFIX}
    container_name: service-aragon-dao-${ENV_SUFFIX}
    build:
      context: .
    env_file:
      - .env.aragon-dao-${ENV_SUFFIX}
    depends_on:
      - rabbitmq
    command: bash -c "yarn wait:rabbitmq && yarn service:aragon-dao"
    healthcheck:
      test: [ 'CMD-SHELL', "pgrep -f 'service:aragon-dao' > /dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal-net
      - public-net

  service-aragon-transfers:
    image: service-aragon-transfers-${ENV_SUFFIX}
    container_name: service-aragon-transfers-${ENV_SUFFIX}
    build:
      context: .
    env_file:
      - .env.aragon-transfers-${ENV_SUFFIX}
    depends_on:
      - rabbitmq
    command: bash -c "yarn wait:rabbitmq && yarn service:aragon-transfers"
    healthcheck:
      test: [ 'CMD-SHELL', "pgrep -f 'service:aragon-transfers' > /dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal-net
      - public-net

  service-aragon-gateway:
    image: service-aragon-gateway-${ENV_SUFFIX}
    container_name: service-aragon-gateway-${ENV_SUFFIX}
    build:
      context: .
    env_file:
      - .env.aragon-gateway-${ENV_SUFFIX}
    depends_on:
      - rabbitmq
    command: bash -c "yarn wait:rabbitmq && yarn service:aragon-gateway"
    healthcheck:
      test: [ 'CMD-SHELL', "pgrep -f 'service:aragon-gateway' > /dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal-net
      - public-net

  service-aragon-plugins:
    image: service-aragon-plugins-${ENV_SUFFIX}
    build:
      context: .
    env_file:
      - .env.aragon-plugins-${ENV_SUFFIX}
    depends_on:
      - rabbitmq
    command: bash -c "yarn wait:rabbitmq && yarn service:aragon-plugins"
    healthcheck:
      test: [ 'CMD-SHELL', "pgrep -f 'service:aragon-plugins' > /dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal-net
      - public-net
    deploy:
      replicas: 1

  service-aragon-rates:
    image: service-aragon-rates-${ENV_SUFFIX}
    container_name: service-aragon-rates-${ENV_SUFFIX}
    build:
      context: .
    env_file:
      - .env.aragon-rates-${ENV_SUFFIX}
    depends_on:
      - rabbitmq
    command: bash -c "yarn wait:rabbitmq && yarn service:aragon-rates"
    healthcheck:
      test: [ 'CMD-SHELL', "pgrep -f 'service:aragon-rates' > /dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal-net
      - public-net

  service-aragon-requeue:
    image: service-aragon-requeue-${ENV_SUFFIX}
    container_name: service-aragon-requeue-${ENV_SUFFIX}
    build:
      context: .
    env_file:
      - .env.aragon-requeue-${ENV_SUFFIX}
    depends_on:
      - rabbitmq
    command: bash -c "yarn wait:rabbitmq && yarn service:aragon-requeue"
    healthcheck:
      test: [ 'CMD-SHELL', "pgrep -f 'service:aragon-requeue' > /dev/null || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    restart: unless-stopped
    networks:
      - internal-net
      - public-net

networks:
  internal-net:
    external: true
    name: internal-net
  public-net:
    external: true
    name: public-net
