const path = require('path')
const dotenv = require('dotenv')

module.exports = {
  apps: [
    {
      name: 'aragon-api',
      cwd: path.resolve(__dirname, ''),
      script: './runners/aragon-api.ts',
      interpreter: 'node',
      interpreter_args: ['-r ts-node/register/transpile-only', '-r tsconfig-paths/register'].join(' '),
      autorestart: true,
      watch: false,
      exec_mode: 'fork',
      min_uptime: '5s',
      restart_delay: 2000,
      env: {
        INSTANCE_ID: 'aragon-api',
        ...dotenv.config({ path: path.resolve(__dirname, '.env.aragon-api') }).parsed,
      },
    },
    {
      name: 'aragon-indexer',
      cwd: path.resolve(__dirname, ''),
      script: './runners/aragon-indexer.ts',
      interpreter: 'node',
      interpreter_args: ['-r ts-node/register/transpile-only', '-r tsconfig-paths/register'].join(' '),
      autorestart: true,
      watch: false,
      exec_mode: 'fork',
      min_uptime: '5s',
      restart_delay: 2000,
      env: {
        INSTANCE_ID: 'aragon-indexer',
        ...dotenv.config({ path: path.resolve(__dirname, '.env.aragon-indexer') }).parsed,
      },
    },
    {
      name: 'aragon-dao',
      cwd: path.resolve(__dirname, ''),
      script: './runners/aragon-dao.ts',
      interpreter: 'node',
      interpreter_args: ['-r ts-node/register/transpile-only', '-r tsconfig-paths/register'].join(' '),
      autorestart: true,
      watch: false,
      exec_mode: 'fork',
      min_uptime: '5s',
      restart_delay: 2000,
      env: {
        INSTANCE_ID: 'aragon-dao',
        ...dotenv.config({ path: path.resolve(__dirname, '.env.aragon-dao') }).parsed,
      },
    },
    {
      name: 'aragon-transfers',
      cwd: path.resolve(__dirname, ''),
      script: './runners/aragon-transfers.ts',
      interpreter: 'node',
      interpreter_args: ['-r ts-node/register/transpile-only', '-r tsconfig-paths/register'].join(' '),
      autorestart: true,
      watch: false,
      exec_mode: 'fork',
      min_uptime: '5s',
      restart_delay: 2000,
      env: {
        INSTANCE_ID: 'aragon-transfers',
        ...dotenv.config({ path: path.resolve(__dirname, '.env.aragon-transfers') }).parsed,
      },
    },
    {
      name: 'aragon-gateway',
      cwd: path.resolve(__dirname, ''),
      script: './runners/aragon-gateway.ts',
      interpreter: 'node',
      interpreter_args: ['-r ts-node/register/transpile-only', '-r tsconfig-paths/register'].join(' '),
      autorestart: true,
      watch: false,
      exec_mode: 'fork',
      min_uptime: '5s',
      restart_delay: 2000,
      env: {
        INSTANCE_ID: 'aragon-gateway',
        ...dotenv.config({ path: path.resolve(__dirname, '.env.aragon-gateway') }).parsed,
      },
    },
    {
      name: 'aragon-plugins',
      cwd: path.resolve(__dirname, ''),
      script: './runners/aragon-plugins.ts',
      interpreter: 'node',
      interpreter_args: ['-r ts-node/register/transpile-only', '-r tsconfig-paths/register'].join(' '),
      autorestart: true,
      watch: false,
      exec_mode: 'fork',
      min_uptime: '5s',
      restart_delay: 2000,
      env: {
        INSTANCE_ID: 'aragon-plugins',
        ...dotenv.config({ path: path.resolve(__dirname, '.env.aragon-plugins') }).parsed,
      },
    },
    {
      name: 'aragon-rates',
      cwd: path.resolve(__dirname, ''),
      script: './runners/aragon-rates.ts',
      interpreter: 'node',
      interpreter_args: ['-r ts-node/register/transpile-only', '-r tsconfig-paths/register'].join(' '),
      autorestart: true,
      watch: false,
      exec_mode: 'fork',
      min_uptime: '5s',
      restart_delay: 2000,
      env: {
        INSTANCE_ID: 'aragon-rates',
        ...dotenv.config({ path: path.resolve(__dirname, '.env.aragon-rates') }).parsed,
      },
    },
    {
      name: 'aragon-admin-api',
      cwd: path.resolve(__dirname, ''),
      script: './runners/aragon-admin-api.ts',
      interpreter: 'node',
      interpreter_args: ['-r ts-node/register/transpile-only', '-r tsconfig-paths/register'].join(' '),
      autorestart: true,
      watch: false,
      exec_mode: 'fork',
      min_uptime: '5s',
      restart_delay: 2000,
      env: {
        INSTANCE_ID: 'aragon-admin-api',
        ...dotenv.config({ path: path.resolve(__dirname, '.env.aragon-admin-api') }).parsed,
      },
    },
    {
      name: 'migration',
      cwd: path.resolve(__dirname, ''),
      script: './runners/migration.ts',
      interpreter: 'node',
      interpreter_args: ['-r ts-node/register/transpile-only', '-r tsconfig-paths/register'].join(' '),
      autorestart: false,
      watch: false,
      exec_mode: 'fork',
      max_restarts: 0,
      min_uptime: 0,
      stop_exit_codes: [0, 1, 2],
      env: {
        INSTANCE_ID: 'migration',
        NODE_ENV: 'production',
        ...dotenv.config({ path: path.resolve(__dirname, '.env.aragon-indexer') }).parsed,
      },
    },
  ],
}
