export const ExitQueue = {
  _format: 'hh-sol-artifact-1',
  contractName: 'ExitQueue',
  sourceName: 'ExitQueue.sol',
  abi: [
    {
      type: 'function',
      name: 'canExit',
      inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
      outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'cooldown',
      inputs: [],
      outputs: [{ name: '', type: 'uint48', internalType: 'uint48' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'exit',
      inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
      outputs: [{ name: 'exitAmount', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'feePercent',
      inputs: [],
      outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'minLock',
      inputs: [],
      outputs: [{ name: '', type: 'uint48', internalType: 'uint48' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'queue',
      inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
      outputs: [
        {
          name: '',
          type: 'tuple',
          internalType: 'struct ITicket.Ticket',
          components: [
            { name: 'holder', type: 'address', internalType: 'address' },
            {
              name: 'exitDate',
              type: 'uint256',
              internalType: 'uint256',
            },
          ],
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'queueExit',
      inputs: [
        { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
        {
          name: '_ticketHolder',
          type: 'address',
          internalType: 'address',
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'setCooldown',
      inputs: [{ name: '_cooldown', type: 'uint48', internalType: 'uint48' }],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'setFeePercent',
      inputs: [{ name: '_fee', type: 'uint256', internalType: 'uint256' }],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'setMinLock',
      inputs: [{ name: '_cooldown', type: 'uint48', internalType: 'uint48' }],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'ticketHolder',
      inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
      outputs: [{ name: '', type: 'address', internalType: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'withdraw',
      inputs: [{ name: '_amount', type: 'uint256', internalType: 'uint256' }],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'event',
      name: 'CooldownSet',
      inputs: [{ name: 'cooldown', type: 'uint48', indexed: false, internalType: 'uint48' }],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'Exit',
      inputs: [
        { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
        {
          name: 'fee',
          type: 'uint256',
          indexed: false,
          internalType: 'uint256',
        },
      ],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'ExitQueuedV2',
      inputs: [
        { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
        {
          name: 'holder',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
        { name: 'queuedAt', type: 'uint48', indexed: false, internalType: 'uint256' },
      ],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'ExitQueued',
      inputs: [
        { name: 'tokenId', type: 'uint256', indexed: true, internalType: 'uint256' },
        {
          name: 'holder',
          type: 'address',
          indexed: true,
          internalType: 'address',
        },
        { name: 'exitDate', type: 'uint256', indexed: false, internalType: 'uint256' },
      ],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'FeePercentSet',
      inputs: [{ name: 'feePercent', type: 'uint256', indexed: false, internalType: 'uint256' }],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'MinLockSet',
      inputs: [{ name: 'minLock', type: 'uint48', indexed: false, internalType: 'uint48' }],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'Withdraw',
      inputs: [
        { name: 'to', type: 'address', indexed: true, internalType: 'address' },
        {
          name: 'amount',
          type: 'uint256',
          indexed: false,
          internalType: 'uint256',
        },
      ],
      anonymous: false,
    },
    { type: 'error', name: 'AlreadyQueued', inputs: [] },
    {
      type: 'error',
      name: 'CannotExit',
      inputs: [],
    },
    { type: 'error', name: 'CooldownTooHigh', inputs: [] },
    {
      type: 'error',
      name: 'FeeTooHigh',
      inputs: [{ name: 'maxFee', type: 'uint256', internalType: 'uint256' }],
    },
    {
      type: 'error',
      name: 'MinLockNotReached',
      inputs: [
        { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
        {
          name: 'minLock',
          type: 'uint48',
          internalType: 'uint48',
        },
        { name: 'earliestExitDate', type: 'uint48', internalType: 'uint48' },
      ],
    },
    { type: 'error', name: 'MinLockOutOfBounds', inputs: [] },
    {
      type: 'error',
      name: 'NoLockBalance',
      inputs: [],
    },
    { type: 'error', name: 'OnlyEscrow', inputs: [] },
    { type: 'error', name: 'ZeroAddress', inputs: [] },
  ],
  bytecode: '0x',
  deployedBytecode: '0x',
  linkReferences: {},
  deployedLinkReferences: {},
}
