export const VotingEscrowIncreasing = {
  _format: 'hh-sol-artifact-1',
  contractName: 'IVotingEscrowIncreasing',
  sourceName: 'IVotingEscrowIncreasing.sol',
  abi: [
    {
      type: 'function',
      name: 'beginWithdrawal',
      inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'createLock',
      inputs: [{ name: '_value', type: 'uint256', internalType: 'uint256' }],
      outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'createLockFor',
      inputs: [
        { name: '_value', type: 'uint256', internalType: 'uint256' },
        {
          name: '_to',
          type: 'address',
          internalType: 'address',
        },
      ],
      outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'curve',
      inputs: [],
      outputs: [{ name: '', type: 'address', internalType: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'isApprovedOrOwner',
      inputs: [
        { name: 'spender', type: 'address', internalType: 'address' },
        {
          name: 'tokenId',
          type: 'uint256',
          internalType: 'uint256',
        },
      ],
      outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'isVoting',
      inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
      outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'lockNFT',
      inputs: [],
      outputs: [{ name: '', type: 'address', internalType: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'locked',
      inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
      outputs: [
        {
          name: '',
          type: 'tuple',
          internalType: 'struct ILockedBalanceIncreasing.LockedBalance',
          components: [
            { name: 'amount', type: 'uint208', internalType: 'uint208' },
            {
              name: 'start',
              type: 'uint48',
              internalType: 'uint48',
            },
          ],
        },
      ],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'queue',
      inputs: [],
      outputs: [{ name: '', type: 'address', internalType: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'setVoter',
      inputs: [{ name: '_voter', type: 'address', internalType: 'address' }],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'sweep',
      inputs: [],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'sweepNFT',
      inputs: [
        { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
        {
          name: '_to',
          type: 'address',
          internalType: 'address',
        },
      ],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'function',
      name: 'token',
      inputs: [],
      outputs: [{ name: '', type: 'address', internalType: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'totalLocked',
      inputs: [],
      outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'totalVotingPower',
      inputs: [],
      outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'totalVotingPowerAt',
      inputs: [{ name: '_t', type: 'uint256', internalType: 'uint256' }],
      outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'voter',
      inputs: [],
      outputs: [{ name: '', type: 'address', internalType: 'address' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'votingPower',
      inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
      outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'votingPowerAt',
      inputs: [
        { name: '_tokenId', type: 'uint256', internalType: 'uint256' },
        {
          name: '_t',
          type: 'uint256',
          internalType: 'uint256',
        },
      ],
      outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'minDeposit',
      inputs: [],
      outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'votingPowerForAccount',
      inputs: [{ name: '_account', type: 'address', internalType: 'address' }],
      outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
      stateMutability: 'view',
    },
    {
      type: 'function',
      name: 'withdraw',
      inputs: [{ name: '_tokenId', type: 'uint256', internalType: 'uint256' }],
      outputs: [],
      stateMutability: 'nonpayable',
    },
    {
      type: 'event',
      name: 'Deposit',
      inputs: [
        { name: 'depositor', type: 'address', indexed: true, internalType: 'address' },
        {
          name: 'tokenId',
          type: 'uint256',
          indexed: true,
          internalType: 'uint256',
        },
        { name: 'startTs', type: 'uint256', indexed: true, internalType: 'uint256' },
        {
          name: 'value',
          type: 'uint256',
          indexed: false,
          internalType: 'uint256',
        },
        { name: 'newTotalLocked', type: 'uint256', indexed: false, internalType: 'uint256' },
      ],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'MinDepositSet',
      inputs: [{ name: 'minDeposit', type: 'uint256', indexed: false, internalType: 'uint256' }],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'Sweep',
      inputs: [
        { name: 'to', type: 'address', indexed: true, internalType: 'address' },
        {
          name: 'amount',
          type: 'uint256',
          indexed: false,
          internalType: 'uint256',
        },
      ],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'SweepNFT',
      inputs: [
        { name: 'to', type: 'address', indexed: true, internalType: 'address' },
        {
          name: 'tokenId',
          type: 'uint256',
          indexed: false,
          internalType: 'uint256',
        },
      ],
      anonymous: false,
    },
    {
      type: 'event',
      name: 'Withdraw',
      inputs: [
        { name: 'depositor', type: 'address', indexed: true, internalType: 'address' },
        {
          name: 'tokenId',
          type: 'uint256',
          indexed: true,
          internalType: 'uint256',
        },
        { name: 'value', type: 'uint256', indexed: false, internalType: 'uint256' },
        {
          name: 'ts',
          type: 'uint256',
          indexed: false,
          internalType: 'uint256',
        },
        { name: 'newTotalLocked', type: 'uint256', indexed: false, internalType: 'uint256' },
      ],
      anonymous: false,
    },
    { type: 'error', name: 'AlreadyVoted', inputs: [] },
    {
      type: 'error',
      name: 'AmountTooSmall',
      inputs: [],
    },
    { type: 'error', name: 'CannotExit', inputs: [] },
    {
      type: 'error',
      name: 'LockNFTAlreadySet',
      inputs: [],
    },
    { type: 'error', name: 'MustBe18Decimals', inputs: [] },
    {
      type: 'error',
      name: 'NoLockFound',
      inputs: [],
    },
    { type: 'error', name: 'NoOwner', inputs: [] },
    {
      type: 'error',
      name: 'NonExistentToken',
      inputs: [],
    },
    { type: 'error', name: 'NotApprovedOrOwner', inputs: [] },
    {
      type: 'error',
      name: 'NotOwner',
      inputs: [],
    },
    { type: 'error', name: 'NotSameOwner', inputs: [] },
    {
      type: 'error',
      name: 'NotTicketHolder',
      inputs: [],
    },
    { type: 'error', name: 'NotVoter', inputs: [] },
    {
      type: 'error',
      name: 'NothingToSweep',
      inputs: [],
    },
    { type: 'error', name: 'OnlyIVotesAdapter', inputs: [] },
    {
      type: 'error',
      name: 'OnlyLockNFT',
      inputs: [],
    },
    { type: 'error', name: 'OwnershipChange', inputs: [] },
    {
      type: 'error',
      name: 'SameAddress',
      inputs: [],
    },
    { type: 'error', name: 'TransferBalanceIncorrect', inputs: [] },
    {
      type: 'error',
      name: 'ZeroAddress',
      inputs: [],
    },
    { type: 'error', name: 'ZeroAmount', inputs: [] },
    { type: 'error', name: 'ZeroBalance', inputs: [] },
  ],
  bytecode: '0x',
  deployedBytecode: '0x',
  linkReferences: {},
  deployedLinkReferences: {},
}
