export const VotingEscrowAdapter = {
  _format: 'hh-sol-artifact-1',
  contractName: 'IVotingEscrowIncreasing',
  sourceName: 'IVotingEscrowIncreasing.sol',
  abi: [
    { inputs: [], stateMutability: 'nonpayable', type: 'constructor' },
    {
      inputs: [
        {
          internalType: 'address',
          name: 'dao',
          type: 'address',
        },
        { internalType: 'address', name: 'where', type: 'address' },
        {
          internalType: 'address',
          name: 'who',
          type: 'address',
        },
        { internalType: 'bytes32', name: 'permissionId', type: 'bytes32' },
      ],
      name: 'DaoUnauthorized',
      type: 'error',
    },
    { inputs: [], name: 'DelegateBySigNotSupported', type: 'error' },
    {
      inputs: [],
      name: 'DelegateeNotSet',
      type: 'error',
    },
    { inputs: [], name: 'DelegationNotAllowed', type: 'error' },
    {
      inputs: [],
      name: 'InvalidTokenId',
      type: 'error',
    },
    { inputs: [], name: 'NotApprovedOrOwner', type: 'error' },
    {
      inputs: [],
      name: 'OnlyEscrow',
      type: 'error',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
      name: 'TokenAlreadyDelegated',
      type: 'error',
    },
    { inputs: [], name: 'TokenListEmpty', type: 'error' },
    {
      inputs: [
        {
          internalType: 'uint256',
          name: 'tokenId',
          type: 'uint256',
        },
      ],
      name: 'TokenNotDelegated',
      type: 'error',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
      name: 'VotingPowerZero',
      type: 'error',
    },
    {
      anonymous: false,
      inputs: [
        {
          indexed: false,
          internalType: 'address',
          name: 'previousAdmin',
          type: 'address',
        },
        { indexed: false, internalType: 'address', name: 'newAdmin', type: 'address' },
      ],
      name: 'AdminChanged',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'delegate', type: 'address' },
        {
          indexed: false,
          internalType: 'bool',
          name: 'enabled',
          type: 'bool',
        },
      ],
      name: 'AutoDelegationSet',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, internalType: 'address', name: 'beacon', type: 'address' }],
      name: 'BeaconUpgraded',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'delegator', type: 'address' },
        {
          indexed: true,
          internalType: 'address',
          name: 'fromDelegate',
          type: 'address',
        },
        { indexed: true, internalType: 'address', name: 'toDelegate', type: 'address' },
      ],
      name: 'DelegateChanged',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'delegate', type: 'address' },
        {
          indexed: false,
          internalType: 'uint256',
          name: 'previousBalance',
          type: 'uint256',
        },
        { indexed: false, internalType: 'uint256', name: 'newBalance', type: 'uint256' },
      ],
      name: 'DelegateVotesChanged',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'uint8', name: 'version', type: 'uint8' }],
      name: 'Initialized',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
      name: 'Paused',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
        {
          indexed: true,
          internalType: 'address',
          name: 'delegatee',
          type: 'address',
        },
        { indexed: false, internalType: 'uint256[]', name: 'tokenIds', type: 'uint256[]' },
      ],
      name: 'TokensDelegated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [
        { indexed: true, internalType: 'address', name: 'sender', type: 'address' },
        {
          indexed: true,
          internalType: 'address',
          name: 'delegatee',
          type: 'address',
        },
        { indexed: false, internalType: 'uint256[]', name: 'tokenIds', type: 'uint256[]' },
      ],
      name: 'TokensUndelegated',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: false, internalType: 'address', name: 'account', type: 'address' }],
      name: 'Unpaused',
      type: 'event',
    },
    {
      anonymous: false,
      inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
      name: 'Upgraded',
      type: 'event',
    },
    {
      inputs: [],
      name: 'DELEGATION_ADMIN_ROLE',
      outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_account', type: 'address' }],
      name: 'autoDelegationDisabled',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_account', type: 'address' }],
      name: 'balanceOf',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '_delegatee', type: 'address' },
        {
          internalType: 'uint256',
          name: '_transitionCount',
          type: 'uint256',
        },
      ],
      name: 'checkpointTransition',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'clock',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'dao',
      outputs: [{ internalType: 'contract IDAO', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256[]', name: '_tokenIds', type: 'uint256[]' }],
      name: 'delegate',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_delegatee', type: 'address' }],
      name: 'delegate',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '', type: 'address' },
        {
          internalType: 'uint256',
          name: '',
          type: 'uint256',
        },
        { internalType: 'uint256', name: '', type: 'uint256' },
        {
          internalType: 'uint8',
          name: '',
          type: 'uint8',
        },
        { internalType: 'bytes32', name: '', type: 'bytes32' },
        {
          internalType: 'bytes32',
          name: '',
          type: 'bytes32',
        },
      ],
      name: 'delegateBySig',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_account', type: 'address' }],
      name: 'delegates',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'escrow',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256[]', name: '_tokenIds', type: 'uint256[]' }],
      name: 'getDelegatedTokens',
      outputs: [{ internalType: 'uint256[]', name: '', type: 'uint256[]' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: '_timestamp', type: 'uint256' }],
      name: 'getPastTotalSupply',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '_account', type: 'address' },
        {
          internalType: 'uint256',
          name: '_timestamp',
          type: 'uint256',
        },
      ],
      name: 'getPastVotes',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_account', type: 'address' }],
      name: 'getVotes',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'implementation',
      outputs: [{ internalType: 'address', name: '', type: 'address' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '_dao', type: 'address' },
        {
          internalType: 'address',
          name: '_escrow',
          type: 'address',
        },
        { internalType: 'address', name: '_clock', type: 'address' },
        {
          internalType: 'bool',
          name: '_startPaused',
          type: 'bool',
        },
      ],
      name: 'initialize',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '', type: 'address' }],
      name: 'latestPointIndex',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: '_from', type: 'address' },
        {
          internalType: 'address',
          name: '_to',
          type: 'address',
        },
        { internalType: 'uint256', name: '_tokenId', type: 'uint256' },
        {
          components: [
            {
              internalType: 'uint208',
              name: 'amount',
              type: 'uint208',
            },
            { internalType: 'uint48', name: 'start', type: 'uint48' },
          ],
          internalType: 'struct ILockedBalanceIncreasing.LockedBalance',
          name: '_locked',
          type: 'tuple',
        },
      ],
      name: 'moveDelegateVotes',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '', type: 'address' }],
      name: 'numberOfDelegatedTokens',
      outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
      stateMutability: 'view',
      type: 'function',
    },
    { inputs: [], name: 'pause', outputs: [], stateMutability: 'nonpayable', type: 'function' },
    {
      inputs: [],
      name: 'paused',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [],
      name: 'proxiableUUID',
      outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: '_delegatee', type: 'address' }],
      name: 'redelegate',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'bool', name: '_disabled', type: 'bool' }],
      name: 'setAutoDelegationDisabled',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256', name: 'tokenId', type: 'uint256' }],
      name: 'tokenIsDelegated',
      outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
      stateMutability: 'view',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'uint256[]', name: '_tokenIds', type: 'uint256[]' }],
      name: 'undelegate',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [],
      name: 'unpause',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [{ internalType: 'address', name: 'newImplementation', type: 'address' }],
      name: 'upgradeTo',
      outputs: [],
      stateMutability: 'nonpayable',
      type: 'function',
    },
    {
      inputs: [
        { internalType: 'address', name: 'newImplementation', type: 'address' },
        {
          internalType: 'bytes',
          name: 'data',
          type: 'bytes',
        },
      ],
      name: 'upgradeToAndCall',
      outputs: [],
      stateMutability: 'payable',
      type: 'function',
    },
  ],
  bytecode: '0x',
  deployedBytecode: '0x',
  linkReferences: {},
  deployedLinkReferences: {},
}
