export enum AlchemyNetwork {
  ETH_MAINNET = 'eth-mainnet',
  ETH_SEPOLIA = 'eth-sepolia',
  ETH_HOLESKY = 'eth-holesky',
  OPT_MAINNET = 'opt-mainnet',
  OPT_SEPOLIA = 'opt-sepolia',
  ARB_MAINNET = 'arb-mainnet',
  ARB_SEPOLIA = 'arb-sepolia',
  MATIC_MAINNET = 'polygon-mainnet',
  MATIC_AMOY = 'polygon-amoy',
  ASTAR_MAINNET = 'astar-mainnet',
  POLYGONZKEVM_MAINNET = 'polygonzkevm-mainnet',
  POLYGONZKEVM_CARDONA = 'polygonzkevm-cardona',
  BASE_MAINNET = 'base-mainnet',
  BASE_SEPOLIA = 'base-sepolia',
  ZKSYNC_MAINNET = 'zksync-mainnet',
  ZKSYNC_SEPOLIA = 'zksync-sepolia',
  SHAPE_MAINNET = 'shape-mainnet',
  SHAPE_SEPOLIA = 'shape-sepolia',
  LINEA_MAINNET = 'linea-mainnet',
  LINEA_SEPOLIA = 'linea-sepolia',
  FANTOM_MAINNET = 'fantom-mainnet',
  FANTOM_TESTNET = 'fantom-testnet',
  ZETACHAIN_MAINNET = 'zetachain-mainnet',
  ZETACHAIN_TESTNET = 'zetachain-testnet',
  ARBNOVA_MAINNET = 'arbnova-mainnet',
  BLAST_MAINNET = 'blast-mainnet',
  BLAST_SEPOLIA = 'blast-sepolia',
  MANTLE_MAINNET = 'mantle-mainnet',
  MANTLE_SEPOLIA = 'mantle-sepolia',
  SCROLL_MAINNET = 'scroll-mainnet',
  SCROLL_SEPOLIA = 'scroll-sepolia',
  GNOSIS_MAINNET = 'gnosis-mainnet',
  GNOSIS_CHIADO = 'gnosis-chiado',
  BNB_MAINNET = 'bnb-mainnet',
  BNB_TESTNET = 'bnb-testnet',
  AVAX_MAINNET = 'avax-mainnet',
  AVAX_FUJI = 'avax-fuji',
  CELO_MAINNET = 'celo-mainnet',
  CELO_ALFAJORES = 'celo-alfajores',
  METIS_MAINNET = 'metis-mainnet',
  OPBNB_MAINNET = 'opbnb-mainnet',
  OPBNB_TESTNET = 'opbnb-testnet',
  CHILIZ_MAINNET = 'chiliz-mainnet',
  BERACHAIN_BARTIO = 'berachain-bartio',
  BERACHAIN_MAINNET = 'berachain-mainnet',
  SONEIUM_MAINNET = 'soneium-mainnet',
  SONEIUM_MINATO = 'soneium-minato',
  WORLDCHAIN_MAINNET = 'worldchain-mainnet',
  WORLDCHAIN_SEPOLIA = 'worldchain-sepolia',
  ROOTSTOCK_MAINNET = 'rootstock-mainnet',
  ROOTSTOCK_TESTNET = 'rootstock-testnet',
  FLOW_MAINNET = 'flow-mainnet',
  FLOW_TESTNET = 'flow-testnet',
  ZORA_MAINNET = 'zora-mainnet',
  ZORA_SEPOLIA = 'zora-sepolia',
  FRAX_MAINNET = 'frax-mainnet',
  FRAX_SEPOLIA = 'frax-sepolia',
  POLYNOMIAL_MAINNET = 'polynomial-mainnet',
  POLYNOMIAL_SEPOLIA = 'polynomial-sepolia',
  CROSSFI_MAINNET = 'crossfi-mainnet',
  CROSSFI_TESTNET = 'crossfi-testnet',
  APECHAIN_MAINNET = 'apechain-mainnet',
  APECHAIN_CURTIS = 'apechain-curtis',
  LENS_SEPOLIA = 'lens-sepolia',
  GEIST_MAINNET = 'geist-mainnet',
  GEIST_POLTER = 'geist-polter',
  LUMIA_PRISM = 'lumia-prism',
  LUMIA_TESTNET = 'lumia-testnet',
  UNICHAIN_MAINNET = 'unichain-mainnet',
  UNICHAIN_SEPOLIA = 'unichain-sepolia',
  SONIC_MAINNET = 'sonic-mainnet',
  SONIC_BLAZE = 'sonic-blaze',
  XMTP_TESTNET = 'xmtp-testnet',
  ABSTRACT_MAINNET = 'abstract-mainnet',
  ABSTRACT_TESTNET = 'abstract-testnet',
  DEGEN_MAINNET = 'degen-mainnet',
  INK_MAINNET = 'ink-mainnet',
  INK_SEPOLIA = 'ink-sepolia',
  SEI_TESTNET = 'sei-testnet',
  RONIN_MAINNET = 'ronin-mainnet',
  RONIN_SAIGON = 'ronin-saigon',
}

export const alchemyNetworkToUrl: Record<string, string> = {
  // Ethereum networks
  [AlchemyNetwork.ETH_MAINNET]: 'eth-mainnet.g.alchemy.com',
  [AlchemyNetwork.ETH_SEPOLIA]: 'eth-sepolia.g.alchemy.com',
  [AlchemyNetwork.ETH_HOLESKY]: 'eth-holesky.g.alchemy.com',

  // Optimism networks
  [AlchemyNetwork.OPT_MAINNET]: 'opt-mainnet.g.alchemy.com',
  [AlchemyNetwork.OPT_SEPOLIA]: 'opt-sepolia.g.alchemy.com',

  // Arbitrum networks
  [AlchemyNetwork.ARB_MAINNET]: 'arb-mainnet.g.alchemy.com',
  [AlchemyNetwork.ARB_SEPOLIA]: 'arb-sepolia.g.alchemy.com',
  [AlchemyNetwork.ARBNOVA_MAINNET]: 'arbnova-mainnet.g.alchemy.com',

  // Polygon networks
  [AlchemyNetwork.MATIC_MAINNET]: 'polygon-mainnet.g.alchemy.com',
  [AlchemyNetwork.MATIC_AMOY]: 'polygon-amoy.g.alchemy.com',
  [AlchemyNetwork.POLYGONZKEVM_MAINNET]: 'polygonzkevm-mainnet.g.alchemy.com',
  [AlchemyNetwork.POLYGONZKEVM_CARDONA]: 'polygonzkevm-cardona.g.alchemy.com',

  // Base networks
  [AlchemyNetwork.BASE_MAINNET]: 'base-mainnet.g.alchemy.com',
  [AlchemyNetwork.BASE_SEPOLIA]: 'base-sepolia.g.alchemy.com',

  // zkSync networks
  [AlchemyNetwork.ZKSYNC_MAINNET]: 'zksync-mainnet.g.alchemy.com',
  [AlchemyNetwork.ZKSYNC_SEPOLIA]: 'zksync-sepolia.g.alchemy.com',

  // Other L2/L1 networks
  [AlchemyNetwork.ASTAR_MAINNET]: 'astar-mainnet.g.alchemy.com',
  [AlchemyNetwork.SHAPE_MAINNET]: 'shape-mainnet.g.alchemy.com',
  [AlchemyNetwork.SHAPE_SEPOLIA]: 'shape-sepolia.g.alchemy.com',
  [AlchemyNetwork.LINEA_MAINNET]: 'linea-mainnet.g.alchemy.com',
  [AlchemyNetwork.LINEA_SEPOLIA]: 'linea-sepolia.g.alchemy.com',
  [AlchemyNetwork.FANTOM_MAINNET]: 'fantom-mainnet.g.alchemy.com',
  [AlchemyNetwork.FANTOM_TESTNET]: 'fantom-testnet.g.alchemy.com',
  [AlchemyNetwork.ZETACHAIN_MAINNET]: 'zetachain-mainnet.g.alchemy.com',
  [AlchemyNetwork.ZETACHAIN_TESTNET]: 'zetachain-testnet.g.alchemy.com',
  [AlchemyNetwork.BLAST_MAINNET]: 'blast-mainnet.g.alchemy.com',
  [AlchemyNetwork.BLAST_SEPOLIA]: 'blast-sepolia.g.alchemy.com',
  [AlchemyNetwork.MANTLE_MAINNET]: 'mantle-mainnet.g.alchemy.com',
  [AlchemyNetwork.MANTLE_SEPOLIA]: 'mantle-sepolia.g.alchemy.com',
  [AlchemyNetwork.SCROLL_MAINNET]: 'scroll-mainnet.g.alchemy.com',
  [AlchemyNetwork.SCROLL_SEPOLIA]: 'scroll-sepolia.g.alchemy.com',
  [AlchemyNetwork.GNOSIS_MAINNET]: 'gnosis-mainnet.g.alchemy.com',
  [AlchemyNetwork.GNOSIS_CHIADO]: 'gnosis-chiado.g.alchemy.com',
  [AlchemyNetwork.BNB_MAINNET]: 'bnb-mainnet.g.alchemy.com',
  [AlchemyNetwork.BNB_TESTNET]: 'bnb-testnet.g.alchemy.com',
  [AlchemyNetwork.AVAX_MAINNET]: 'avax-mainnet.g.alchemy.com',
  [AlchemyNetwork.AVAX_FUJI]: 'avax-fuji.g.alchemy.com',
  [AlchemyNetwork.CELO_MAINNET]: 'celo-mainnet.g.alchemy.com',
  [AlchemyNetwork.CELO_ALFAJORES]: 'celo-alfajores.g.alchemy.com',
  [AlchemyNetwork.METIS_MAINNET]: 'metis-mainnet.g.alchemy.com',
  [AlchemyNetwork.OPBNB_MAINNET]: 'opbnb-mainnet.g.alchemy.com',
  [AlchemyNetwork.OPBNB_TESTNET]: 'opbnb-testnet.g.alchemy.com',
  [AlchemyNetwork.CHILIZ_MAINNET]: 'chiliz-mainnet.g.alchemy.com',
  [AlchemyNetwork.BERACHAIN_BARTIO]: 'berachain-bartio.g.alchemy.com',
  [AlchemyNetwork.BERACHAIN_MAINNET]: 'berachain-mainnet.g.alchemy.com',
  [AlchemyNetwork.SONEIUM_MAINNET]: 'soneium-mainnet.g.alchemy.com',
  [AlchemyNetwork.SONEIUM_MINATO]: 'soneium-minato.g.alchemy.com',
  [AlchemyNetwork.WORLDCHAIN_MAINNET]: 'worldchain-mainnet.g.alchemy.com',
  [AlchemyNetwork.WORLDCHAIN_SEPOLIA]: 'worldchain-sepolia.g.alchemy.com',
  [AlchemyNetwork.ROOTSTOCK_MAINNET]: 'rootstock-mainnet.g.alchemy.com',
  [AlchemyNetwork.ROOTSTOCK_TESTNET]: 'rootstock-testnet.g.alchemy.com',
  [AlchemyNetwork.FLOW_MAINNET]: 'flow-mainnet.g.alchemy.com',
  [AlchemyNetwork.FLOW_TESTNET]: 'flow-testnet.g.alchemy.com',
  [AlchemyNetwork.ZORA_MAINNET]: 'zora-mainnet.g.alchemy.com',
  [AlchemyNetwork.ZORA_SEPOLIA]: 'zora-sepolia.g.alchemy.com',
  [AlchemyNetwork.FRAX_MAINNET]: 'frax-mainnet.g.alchemy.com',
  [AlchemyNetwork.FRAX_SEPOLIA]: 'frax-sepolia.g.alchemy.com',
  [AlchemyNetwork.POLYNOMIAL_MAINNET]: 'polynomial-mainnet.g.alchemy.com',
  [AlchemyNetwork.POLYNOMIAL_SEPOLIA]: 'polynomial-sepolia.g.alchemy.com',
  [AlchemyNetwork.CROSSFI_MAINNET]: 'crossfi-mainnet.g.alchemy.com',
  [AlchemyNetwork.CROSSFI_TESTNET]: 'crossfi-testnet.g.alchemy.com',
  [AlchemyNetwork.APECHAIN_MAINNET]: 'apechain-mainnet.g.alchemy.com',
  [AlchemyNetwork.APECHAIN_CURTIS]: 'apechain-curtis.g.alchemy.com',
  [AlchemyNetwork.LENS_SEPOLIA]: 'lens-sepolia.g.alchemy.com',
  [AlchemyNetwork.GEIST_MAINNET]: 'geist-mainnet.g.alchemy.com',
  [AlchemyNetwork.GEIST_POLTER]: 'geist-polter.g.alchemy.com',
  [AlchemyNetwork.LUMIA_PRISM]: 'lumia-prism.g.alchemy.com',
  [AlchemyNetwork.LUMIA_TESTNET]: 'lumia-testnet.g.alchemy.com',
  [AlchemyNetwork.UNICHAIN_MAINNET]: 'unichain-mainnet.g.alchemy.com',
  [AlchemyNetwork.UNICHAIN_SEPOLIA]: 'unichain-sepolia.g.alchemy.com',
  [AlchemyNetwork.SONIC_MAINNET]: 'sonic-mainnet.g.alchemy.com',
  [AlchemyNetwork.SONIC_BLAZE]: 'sonic-blaze.g.alchemy.com',
  [AlchemyNetwork.XMTP_TESTNET]: 'xmtp-testnet.g.alchemy.com',
  [AlchemyNetwork.ABSTRACT_MAINNET]: 'abstract-mainnet.g.alchemy.com',
  [AlchemyNetwork.ABSTRACT_TESTNET]: 'abstract-testnet.g.alchemy.com',
  [AlchemyNetwork.DEGEN_MAINNET]: 'degen-mainnet.g.alchemy.com',
  [AlchemyNetwork.INK_MAINNET]: 'ink-mainnet.g.alchemy.com',
  [AlchemyNetwork.INK_SEPOLIA]: 'ink-sepolia.g.alchemy.com',
  [AlchemyNetwork.SEI_TESTNET]: 'sei-testnet.g.alchemy.com',
  [AlchemyNetwork.RONIN_MAINNET]: 'ronin-mainnet.g.alchemy.com',
  [AlchemyNetwork.RONIN_SAIGON]: 'ronin-saigon.g.alchemy.com',
}
