export enum IPermission {
  EXECUTE_PROPOSAL_PERMISSION = 'EXECUTE_PROPOSAL_PERMISSION',
  EXECUTE_PERMISSION = 'EXECUTE_PERMISSION',
  MINT_PERMISSION = 'MINT_PERMISSION',
  CREATE_PROPOSAL_PERMISSION = 'CREATE_PROPOSAL_PERMISSION',
  PARENT_TO_SUB_DAO_ACKNOWLEDGEMENT_PERMISSION_ID = 'PARENT_TO_SUB_DAO_ACKNOWLEDGEMENT_PERMISSION_ID',
  SUB_DAO_TO_PARENT_ACKNOWLEDGEMENT_PERMISSION_ID = 'SUB_DAO_TO_PARENT_ACKNOWLEDGEMENT_PERMISSION_ID',
}
