export enum IPermission {
  EXECUTE_PROPOSAL_PERMISSION = 'EXECUTE_PROPOSAL_PERMISSION',
  EXECUTE_PERMISSION = 'EXECUTE_PERMISSION',
  MINT_PERMISSION = 'MINT_PERMISSION',
  CREATE_PROPOSAL_PERMISSION = 'CREATE_PROPOSAL_PERMISSION',
}
