name: API Monitoring

on:
  schedule:
    # - cron: '0 * * * *' # Run performance tests every hour
    - cron: '*/15 * * * *' # Runs every 15 mins
  workflow_dispatch:

env:
  DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - host: 'https://stg.backend.aragon.in'
            env_name: 'App Backend Staging'
          - host: 'https://backend.aragon.in'
            env_name: 'App Backend Production'
          - host: 'https://dev.backend.aragon.in'
            env_name: 'App Backend Development'
      fail-fast: false

    name: Test ${{ matrix.env_name }} (${{ matrix.host }})

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Newman and Reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Run Performance Tests
        id: postman-test
        timeout-minutes: 1
        run: |
          echo "Running tests for ${{ matrix.env_name }} (${{ matrix.host }})"

          # Run Newman tests and save output
          newman run postman/postman-backend-collection.json \
            --env-var "host=${{ matrix.host }}" \
            --reporters cli \
            --timeout-request 120000 \
            > test-output.log || true

          # Display test output for debugging
          echo "===== Newman Test Output for ${{ matrix.host }} ====="
          cat test-output.log
          echo "=================================================="

          # Extract full details of failures
          RAW_FAILURES=$(awk '/#  failure/{flag=1; next} /==============================/{flag=0} flag' test-output.log)
          if [ -z "$RAW_FAILURES" ]; then
            echo "TEST_STATUS=success" >> $GITHUB_ENV
          else
            # Escape newlines and special characters
            SANITIZED_FAILURES=$(echo "$RAW_FAILURES" | sed ':a;N;$!ba;s/\n/\\n/g' | sed 's/"/\\"/g')
            echo "FAILURES=$SANITIZED_FAILURES" >> $GITHUB_ENV
            echo "TEST_STATUS=failed" >> $GITHUB_ENV
            exit 1
          fi

      - name: Push metrics to grafana
        if: always()
        run: |
          #!/bin/bash
          set -x

          ############
          # URL VARS #
          ############
          monitor_endpoint_url="https://monitor.aragon.in/victoria/api/v1/import/prometheus"
          monitor_endpoint_apikey="SECRETVALUE_victoria_metrics_apikey"
          monitor_metric_name="github_actions"
          monitor_timestamp=$(date +%s000)

          #######################
          # Metric (Modify this)#
          #######################

          #Numeric metric Value. This one will be used for alerting
          ## 0 ->   everything went correct
          ## >0 ->  something went bad (probably it will trigger an alert)
          case "${{ steps.postman-test.outcome }}" in
            "success")
              METRIC_VALUE=0
              ;;
            "failure")
              METRIC_VALUE=1
              ;;
            "cancelled")
              METRIC_VALUE=1
              ;;
            "skipped")
              METRIC_VALUE=1
              ;;
            *)
              METRIC_VALUE=1
              ;;
          esac


          ############################
          # File with all the labels #
          ############################
          cat << EOF > metrics_labels

          # Monitor variables
          monitor_version="v0.1" #Metric used to differentiate between several metric configs

          # Github metadata
          github_ref_name="${{ github.ref_name }}" #name of the branch
          github_ref_sha="${{ github.sha }}" #hash of the branch used by workflow
          github_workflow_ref="${{github.workflow_ref}}" ##full ref, with repo, workflow path..
          github_event_name="${{ github.event_name }}" ##Tells you if it was launched using trigger, cron, pr...
          github_runid="${{github.run_id}}" #Unique workflow run, changes on each execution
          github_workflow_name="${{ github.workflow }}"

          ########################################
          # Labels to be specified (Modify this) #
          ########################################

          # Project Variables
          environment="${{ matrix.env_name }}" # previ,dev,stg,prod
          project="backend2" #app-next, backend2, infra...
          subproject="api-monitoring" #To be able to make categories if needed

          #Extras Labels
          ## Here you can add all the labels you want to use
          ## Remember to add them to the url. i.e:
          test_result_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          test_error_message="API Monitoring failed"
          env_host="${{ matrix.host }}"


          EOF

          ########################################
          # Pre-processing and sending the query #
          ########################################

          sed -i 's/#.*//' metrics_labels #remove all commented lines and commentaries
          sed -i 's/[[:space:]]*$//' metrics_labels # remove all trailing whitespaces from each line
          sed -i '/^$/d' metrics_labels # remove empty lines

          cat << EOF >curl_test
          curl -X POST \
            -H "X-API-Key: SECRETVALUE_victoria_metrics_apikey" \
            -H "Content-Type: text/plain" \
            "${monitor_endpoint_url}" \
            -d "${monitor_metric_name}{$(awk -F= '/^[^#]/ {gsub(/"/, "", $2); printf "%s=\\\"%s\\\", \\\n", $1, $2}' metrics_labels)
          } ${METRIC_VALUE}"

          EOF

          bash curl_test

  #     - name: Notify Discord on Failure
  #       if: failure()
  #       env:
  #         FAILURES: ${{ env.FAILURES }}
  #       run: |
  #         echo "Sending Discord failure notification..."

  #         # Create JSON payload
  #         cat <<EOF > payload.json
  #         {
  #           "embeds": [{
  #             "title": "❌ Backend API Monitoring Test Failed",
  #             "color": 15158332,
  #             "fields": [
  #               { "name": "Repository", "value": "aragon/app-backend", "inline": false },
  #               { "name": "Workflow", "value": "AppBackend API Monitoring", "inline": false },
  #               { "name": "Branch", "value": "${{ github.ref }}", "inline": false },
  #               { "name": "Environment", "value": "${{ matrix.host }} (${{ matrix.env_name }})", "inline": false },
  #               { "name": "Details", "value": "[View Failure Details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})", "inline": false }
  #             ],
  #             "timestamp": "$(date --utc +%FT%TZ)"
  #           }]
  #         }
  #         EOF

  #         # Send notification to Discord
  #         curl -X POST -H "Content-Type: application/json" -d @payload.json https://discord.com/api/webhooks/1309183202719699084/7iigCapTmyIHtgkqcLfXY9j557T_YChm7bv9h-BBU37ZhPDIIZYt34Z0KkqQGCBGic1M
  #         echo "Discord notification sent."

  #     - name: Cleanup Temporary Files
  #       run: rm -rf ./node_modules ./build ./tmp

  # weekly_success:
  #   if: github.event.schedule == '0 0 * * 1'
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Notify Discord Weekly Success Message
  #       run: |
  #         echo "Sending Discord weekly success notification..."
  #         cat <<EOF > payload.json
  #         {
  #           "embeds": [{
  #             "title": "✅ Weekly Report: Backend API Monitoring Tests Succeeded!",
  #             "color": 3066993,
  #             "fields": [
  #               { "name": "Repository", "value": "aragon/app-backend", "inline": false },
  #               { "name": "Workflow", "value": "AppBackend API Monitoring", "inline": false },
  #               { "name": "Branch", "value": "${{ github.ref }}", "inline": false },
  #               { "name": "Environment", "value": "${{ matrix.host }} (${{ matrix.env_name }})", "inline": false },
  #               { "name": "Details", "value": "[View Failure Details](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})", "inline": false }
  #             ],
  #             "timestamp": "$(date --utc +%FT%TZ)"
  #           }]
  #         }
  #         EOF

  #         curl -X POST -H "Content-Type: application/json" -d @payload.json https://discord.com/api/webhooks/1309183202719699084/7iigCapTmyIHtgkqcLfXY9j557T_YChm7bv9h-BBU37ZhPDIIZYt34Z0KkqQGCBGic1M
  #         echo "Discord weekly success notification sent."
