name: AppBackend API Monitoring

on:
  schedule:
    - cron: '*/30 * * * *' # Run every 30 minutes
  workflow_dispatch:
    inputs:
      discordWebhookUrl:
        description: 'Discord Webhook URL'
        required: true
        type: string
  push:
    branches:
      - feature/monitor # Trigger on this branch only

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Newman
        run: npm install -g newman

      - name: Run Performance Tests Only
        id: postman-test
        run: |
          # Run Newman tests and save output
          newman run postman/postman-backend-collection.json \
            --env-var "host=https://api.aragon-backend.com" \
            --reporters cli \
            --timeout-request 5000 \
            > test-output.log || true

          # Extract content starting from "GET https://api.aragon-backend.com" and stopping before "=============================="
          MESSAGE_CONTENT=$(awk '/GET https:\/\/api.aragon-backend.com/,/==============================/{if (!/==============================/) print}' test-output.log)
          if [ -z "$MESSAGE_CONTENT" ]; then
            echo "MESSAGE_CONTENT=None" >> $GITHUB_ENV
          else
            SANITIZED_CONTENT=$(echo "$MESSAGE_CONTENT" | jq -Rsa .)
            echo "MESSAGE_CONTENT=$SANITIZED_CONTENT" >> $GITHUB_ENV
          fi

          # Extract full details of failures
          RAW_FAILURES=$(awk '/#  failure/{flag=1; next} /==============================/{flag=0} flag' test-output.log)
          if [ -z "$RAW_FAILURES" ]; then
            echo "FAILURES=None" >> $GITHUB_ENV
          else
            SANITIZED_FAILURES=$(echo "$RAW_FAILURES" | jq -Rsa .)
            echo "FAILURES=$SANITIZED_FAILURES" >> $GITHUB_ENV
          fi

          # Determine test status
          if [ -z "$RAW_FAILURES" ]; then
            echo "TEST_STATUS=success" >> $GITHUB_ENV
          else
            echo "TEST_STATUS=failed" >> $GITHUB_ENV
          fi

      - name: Notify Discord
        run: |
          if [ "${{ env.TEST_STATUS }}" == "failed" ]; then
            curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"❌ **Postman Performance Test Failed**\\n**Details:**\\n${{ env.MESSAGE_CONTENT }}\\n**Failing Tests:**\\n${{ env.FAILURES }}\"}" \
              https://discord.com/api/webhooks/1309183202719699084/7iigCapTmyIHtgkqcLfXY9j557T_YChm7bv9h-BBU37ZhPDIIZYt34Z0KkqQGCBGic1M
          else
            curl -H "Content-Type: application/json" \
              -X POST \
              -d "{\"content\": \"✅ **Postman Performance Test Succeeded**\\n**Details:**\\n${{ env.MESSAGE_CONTENT }}\"}" \
              https://discord.com/api/webhooks/1309183202719699084/7iigCapTmyIHtgkqcLfXY9j557T_YChm7bv9h-BBU37ZhPDIIZYt34Z0KkqQGCBGic1M
          fi
