name: AppBackend Test
on:
  workflow_dispatch:
  push:
    branches-ignore: ## Ignore develop and main branches to avoid an unneeded 2nd build.
      - 'develop'
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Format
        run: yarn format:check
      - name: Lint
        run: yarn lint
      - name: Dot only
        run: yarn test:dotonly
      - name: Test Unit
        run: yarn test:unit:coverage
      - name: Unit Coverage
        run: yarn test:coverage:check
