name: Deploy new version

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set variables
        id: set-variables
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          case "$BRANCH_NAME" in
            main)
              DEPLOY_ENV=prd
              echo "DEPLOY_ENV=prd" >> $GITHUB_ENV

              echo "OP_SERVER_USERNAME=op://apikeys_production/backend2_server_${DEPLOY_ENV}/username" >> $GITHUB_ENV
              echo "OP_SERVER_URL=op://apikeys_production/backend2_server_${DEPLOY_ENV}/URL" >> $GITHUB_ENV
              echo "OP_SERVER_CERT=op://apikeys_production/backend2_server_${DEPLOY_ENV}/deploy_backend2_${DEPLOY_ENV}" >> $GITHUB_ENV
              echo "OP_SERVICE_ACCOUNT_VAR_NAME_SERVERS=OP_SERVICE_ACCOUNT_TOKEN_PROD_TEMP" >> $GITHUB_ENV
              echo "OP_SERVICE_ACCOUNT_VAR_NAME_CONFIGS=OP_SERVICE_ACCOUNT_TOKEN_BACKEND2_TEMP" >> $GITHUB_ENV
              ;;


            staging)
              DEPLOY_ENV=stg
              echo "DEPLOY_ENV=stg" >> $GITHUB_ENV

              echo "OP_SERVER_USERNAME=op://apikeys_nonprod/backend2_server_${DEPLOY_ENV}/username" >> $GITHUB_ENV
              echo "OP_SERVER_URL=op://apikeys_nonprod/backend2_server_${DEPLOY_ENV}/URL" >> $GITHUB_ENV
              echo "OP_SERVER_CERT=op://apikeys_nonprod/backend2_server_${DEPLOY_ENV}/deploy_backend2_${DEPLOY_ENV}" >> $GITHUB_ENV
              echo "OP_SERVICE_ACCOUNT_VAR_NAME_SERVERS=OP_SERVICE_ACCOUNT_TOKEN_NONPROD_TEMP" >> $GITHUB_ENV
              echo "OP_SERVICE_ACCOUNT_VAR_NAME_CONFIGS=OP_SERVICE_ACCOUNT_TOKEN_BACKEND2_TEMP" >> $GITHUB_ENV
              ;;


            *)
              DEPLOY_ENV=dev
              echo "DEPLOY_ENV=dev" >> $GITHUB_ENV

              echo "OP_SERVER_USERNAME=op://apikeys_nonprod/backend2_server_${DEPLOY_ENV}/username" >> $GITHUB_ENV
              echo "OP_SERVER_URL=op://apikeys_nonprod/backend2_server_${DEPLOY_ENV}/URL" >> $GITHUB_ENV
              echo "OP_SERVER_CERT=op://apikeys_nonprod/backend2_server_${DEPLOY_ENV}/deploy_backend2_${DEPLOY_ENV}" >> $GITHUB_ENV
              echo "OP_SERVICE_ACCOUNT_VAR_NAME_SERVERS=OP_SERVICE_ACCOUNT_TOKEN_NONPROD_TEMP" >> $GITHUB_ENV
              echo "OP_SERVICE_ACCOUNT_VAR_NAME_CONFIGS=OP_SERVICE_ACCOUNT_TOKEN_BACKEND2_TEMP" >> $GITHUB_ENV
              ;;
          esac

      - name: Checkout repository branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Load secrets
        id: op-server-secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets[env.OP_SERVICE_ACCOUNT_VAR_NAME_SERVERS] }}
          SERVER_USERNAME: ${{ env.OP_SERVER_USERNAME }}
          SERVER_URL: ${{ env.OP_SERVER_URL }}

      - name: Install 1Password CLI
        uses: 1password/install-cli-action@v1
        with:
          version: latest-beta

      - name: Download certfile
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets[env.OP_SERVICE_ACCOUNT_VAR_NAME_SERVERS] }}
          SERVER_CERT: ${{ env.OP_SERVER_CERT }}
        run: |
          mkdir ~/.ssh/ -p
          op read ${{ env.SERVER_CERT }} > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Download config files
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets[env.OP_SERVICE_ACCOUNT_VAR_NAME_CONFIGS] }}
          OP_VAULT: temporal_backend2
          OP_VAULT_ITEM: configs_app_backend2_${{env.DEPLOY_ENV}}
        run: |
          ls
          op item get --vault "${{env.OP_VAULT}}" "${{env.OP_VAULT_ITEM}}" --format json | jq -r '.fields.[].label'|sed 1d > configs
          while IFS= read -r line; do
          	echo -e "\n $line"
          	op item get --vault "${{env.OP_VAULT}}" "${{env.OP_VAULT_ITEM}}" --fields "$line" | sed '1s/^"//;;$s/"$//' > temp_file
          	IFS=';' read -ra CONFIG_FILES <<< "$line"

            ## Set up specific env configs values for LOGZIO
          	for conf_single in "${CONFIG_FILES[@]}"; do
          		CONFIG_FILE_NAME=".env.$conf_single"
          		cp temp_file "$CONFIG_FILE_NAME"
          		case "${{env.DEPLOY_ENV}}" in
              	prd)
                	echo "Setting up ${{env.DEPLOY_ENV}} environment for $conf_single"
          			  sed -i "s/^LOGZIO_SERVER_NAME=.*/LOGZIO_SERVER_NAME=${conf_single^^}-PRODUCTION / " "$CONFIG_FILE_NAME"
                	;;
              	
                stg)
              		echo "Setting up ${{env.DEPLOY_ENV}} environment for $conf_single"
          		    sed -i "s/^LOGZIO_SERVER_NAME=.*/LOGZIO_SERVER_NAME=${conf_single^^}-STAGING / " "$CONFIG_FILE_NAME"
              		;;
              
                *)
          			  echo "Setting up ${{env.DEPLOY_ENV}} environment for $conf_single"
          			  sed -i "s/^LOGZIO_SERVER_NAME=.*/LOGZIO_SERVER_NAME=${conf_single^^}-DEVELOPMENT / " "$CONFIG_FILE_NAME"
                  ;;
              esac
                  
          		sha256sum $CONFIG_FILE_NAME
          	done
                  
          	rm temp_file
          done < configs

      - name: Print masked secret and branch variable map
        run: |
          echo "Branch variable map: ${{ env.DEPLOY_ENV }}"

      - name: Execute deployment script
        env:
          IS_A_GITHUB_ACTION: true
        run: |
          cd ..
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          bash app-backend/.github/workflows/deployment/deployment.sh -u "${{ steps.op-server-secrets.outputs.SERVER_USERNAME }}" -m "${{ steps.op-server-secrets.outputs.SERVER_URL }}"

      - name: Reset envs
        run: |
              echo "OP_SERVER_USERNAME=" >> $GITHUB_ENV
              echo "OP_SERVER_URL=" >> $GITHUB_ENV
              echo "OP_SERVER_CERT=" >> $GITHUB_ENV
              echo "OP_SERVICE_ACCOUNT_VAR_NAME_SERVERS=" >> $GITHUB_ENV


      - name: Dispatch E2E tests
        uses: aragon/app-qa/.github/actions/dispatch@main
        with:
          opToken: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN_PROD_TEMP }}
          environment: ${{ env.DEPLOY_ENV }}
