name: AppBackend Test
on:
  workflow_dispatch:
  push:
    branches-ignore: ## Ignore develop and main branches to avoid an unneeded 2nd build.
      - 'develop'
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install OpenSSL 1.1 and create symlink for libcrypto.so.1.1
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl1.1
          LIBCRYPTO_PATH=$(find /usr/lib/ -name libcrypto.so.1.1)
          if [ -n "$LIBCRYPTO_PATH" ]; then
            sudo ln -s $LIBCRYPTO_PATH /usr/lib/x86_64-linux-gnu/libcrypto.so
          else
            echo "libcrypto.so.1.1 not found"
            exit 1
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Format
        run: yarn format:check
      - name: Lint
        run: yarn lint
      - name: Dot only
        run: yarn test:dotonly
      - name: Test Unit
        run: yarn test:unit:coverage
      - name: Unit Coverage
        run: yarn test:coverage:check
