name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: yarn install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.ARABOT_PAT }}
        run: echo "$GITHUB_TOKEN" | sha256sum ;npx semantic-release --repository-url "https://github.com/aragon/app-backend.git"

      - name: Get latest release version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')" >> $GITHUB_ENV
