name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: yarn install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

      - name: Get latest release version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')" >> $GITHUB_ENV

  create-pr-staging:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest release version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')" >> $GITHUB_ENV

      - name: Create PR from `main` to `staging`
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'main'
          destination_branch: 'staging'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'chore: release-${{ env.VERSION }}'
          pr_body: 'This PR updates `staging` with release `${{ env.VERSION }}` from `main`.'
      - name: Log PR Failure (if any)
        if: failure()
        run: |
          echo "⚠️ Warning: Failed to create PR from `main` to `staging`, but continuing..."

  create-pr-development:
    needs: create-pr-staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get latest release version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')" >> $GITHUB_ENV

      - name: Create PR from `main` to `development`
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'main'
          destination_branch: 'development'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: 'chore: release-${{ env.VERSION }}'
          pr_body: 'This PR updates `development` with release `${{ env.VERSION }}` from `main`.'

      - name: Log PR Failure (if any)
        if: failure()
        run: |
          echo "⚠️ Warning: Failed to create PR from `staging` to `development`, but continuing..."
