name: Release

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:
  push:
    branches:
      - main
      - development

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: yarn install

      - name: Run Semantic Release (Dry Run for PRs)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Running in Dry Run Mode (PR to Development)"
            npx semantic-release --dry-run --repository-url "https://github.com/aragon/app-backend.git"
          else
            echo "Running Full Release"
            npx semantic-release --repository-url "https://github.com/aragon/app-backend.git"
          fi

      - name: Get latest release version
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0 | sed 's/v//')" >> $GITHUB_ENV
