name: Unit Dep Test
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'development'
      - 'staging'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Build Docker image
        run: |
          docker compose -f docker-compose.yml build unit-dep

  dep-tests:
    runs-on: ubuntu-latest
    needs: build  # Ensure this job waits until the build job completes
    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Run Dep Tests
        run: |
          docker compose -f docker-compose.yml up \
            --exit-code-from unit-dep \
            --abort-on-container-exit

      - name: Teardown containers
        run: docker compose -f docker-compose.yml down
