name: Unit Test
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'development'
      - 'main'

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install OpenSSL 1.1 and create symlink for libcrypto.so.1.1
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
          sudo apt-get install -f  # Install dependencies if needed
      - name: Setup pnpm
        uses: ./.github/actions/setup-pnpm
      - name: Format
        run: pnpm format:check
      - name: Lint
        run: pnpm lint
      - name: Type check
        run: pnpm type-check
      - name: Dot only
        run: pnpm test:dotonly
      - name: Test Unit
        run: pnpm test:unit:coverage
      - name: Unit Coverage
        run: pnpm test:coverage:check
